name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: RSpec Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false
          
      - name: Configure and install
        run: |
          bundle config set deployment false
          bundle config set frozen false
          bundle config set path vendor/bundle
          bundle install
          
      - name: Run tests
        run: bundle exec rspec

  docs:
    name: Build and Deploy Documentation
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false
          
      - name: Configure and install
        run: |
          bundle config set deployment false
          bundle config set frozen false
          bundle config set path vendor/bundle
          bundle install
          
      - name: Generate documentation
        run: |
          bundle exec yard doc
          mv docs/_index.html docs/index.html
          touch docs/.nojekyll
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
