name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: RSpec Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false
          
      - name: Configure and install
        run: |
          bundle config set frozen false
          bundle config set path vendor/bundle
          bundle install
          
      - name: Run tests
        run: bundle exec rspec

  docs:
    name: Build and Deploy Documentation
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false
          
      - name: Configure and install
        run: |
          bundle config set frozen false
          bundle config set path vendor/bundle
          bundle install
          
      - name: Install YARD and dependencies
        run: |
          gem install yard kramdown kramdown-parser-gfm redcarpet
          
      - name: Generate documentation
        run: |
          yard doc --markup markdown --markup-provider kramdown --embed-mixins \
                 --files README.md,LICENSE.md --output-dir ./docs \
                 --title "ISO 1996 Acoustics Library for Ruby" --math mathjax
          mv docs/_index.html docs/index.html
          touch docs/.nojekyll
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: false
