name: Deploy Docs

on:
  push:
    branches: [main]
    paths: ['lib/**', 'README.md', '.yardopts']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Install YARD
        run: gem install yard yard-math

      - name: Generate Documentation
        run: |
          yard doc --math mathjax
          mv docs/_index.html docs/index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
